### PR TITLE
Tip how to format the description in right way 

### PR DESCRIPTION
**Pull request by otanim**

### CODE REVIEW

**Comment by fxfactorial** [comment]
Why three commits though, squash this

**Comment by otanim** [comment]
it's a continuously correction.

**Comment by fxfactorial** [comment]
But final result is one change to the root README.md, not like each commit was a unit of work. Please squash into one commit.

**Comment by fxfactorial** [comment]
Doh, I overeagerly merged

**Comment by fxfactorial** [comment]
@otanim some redundancy in the root README now

**Comment by otanim** [comment]
reference: https://github.com/iteratehackerspace/cheatsheet/pull/43

**Comment by fxfactorial** [comment]
@otanim I love how professional you are

**Comment by otanim** [comment]
@fxfactorial I just know how to use Git and GitHub :)

**Comment by fxfactorial** [comment]
Github let's you do cool things, like you can programmatically reference issues and close issues with the commit message: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by otanim** [comment]
good tip for me, I've seen that how users make an references, but didn't know how to do that, thanks pal :)

**Pull request merged**
