### PR TITLE
Update and rename bubble.md to bubble.cpp

### PR DESCRIPTION
**Pull request by otanim**
Simplify the file name and the content

### CODE REVIEW

**Comment by fxfactorial** [comment]
Yea but now its not pretty syntax blocked. 

There is supposed to be explanation before the code block, i.e. how to compile it, run it, etc. 

Aka needs to be: 

`$ g++ (or clang, I prefer clang) -std=c++14 bubble.cpp -o program`

`$ ./program`

**Comment by otanim** [comment]
I suggest to have this structure
root
|__algorithms
     |__c-plus-plus
          |__README.md (here we will have a list of algorithms with their descriptions)
          |__bubble.cpp (algorithm itself)

**Comment by fxfactorial** [comment]
I assume you mean to put `bubble.cpp` under `c-plus-plus`

**Comment by otanim** [comment]
@fxfactorial I just updated my previous message, please update the page.

**Comment by otanim** [comment]
agreed.

**Comment by fxfactorial** [comment]
I assume you will force push

**Comment by otanim** [comment]
to master ? I don't have permissions for that.

**Comment by fxfactorial** [comment]
No, you force push to your own repo so that we don't have to close this PR. The force push will be reflected here

**Comment by otanim** [comment]
ok, sure.

**Comment by otanim** [comment]
done.

**Comment by kalipsobznuni** [comment]
the branch has some conflicts to be resolved though so we can't merge it now

**Comment by otanim** [comment]
I'm getting confused because of GitHub, or my wrong steps.

**Comment by otanim** [comment]
that's insane. GitHub didn't work correctly.

**Pull request merged**
